# Generated by Django 3.2.7 on 2021-09-19 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawAllNCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True, verbose_name='Название закона')),
                ('all_text', models.TextField(null=True, verbose_name='Описание закона')),
            ],
            options={
                'verbose_name': 'Законы',
            },
        ),
        migrations.CreateModel(
            name='NCOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300, verbose_name='Название законодательство')),
            ],
            options={
                'verbose_name': 'Законодательство об НCО',
            },
        ),
        migrations.CreateModel(
            name='ProjectFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectFavourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.lawallnco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное законов ',
            },
        ),
        migrations.AddField(
            model_name='lawallnco',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ncocategory', verbose_name='Категория'),
        ),
    ]
